### ISSUE TITLE
Build failure on fresh clone, using IntelliJ

### ISSUE THREAD

**Issue by OliverNChalk** [vechain/thor-client-sdk4j#17]
I freshly cloned the repo and ran install using IntelliJ's Maven Lifecycle manager. I got the following result:

![image](https://user-images.githubusercontent.com/11343499/52919195-de83ea00-3353-11e9-91d4-e7b23f7159fe.png)

**Comment by OliverNChalk** [comment]
I believe the issue is due to there being no vechain node found at localhost:8669. I will verify this when I get home

**Comment by potti** [comment]
hi OliverNChalk, you could use -Dmaven.test.skip=true to skip test

**Comment by OliverNChalk** [comment]
Yep, issue was related to no node on localhost
